version: '3.9'

services:
  app:
    container_name: todolist-app
    env_file:
      - .env
    environment:
      APP_LOG_LEVEL: ${APP_LOG_LEVEL}
      APP_ENV: ${APP_ENV}
      APP_NAME: ${APP_NAME}
      APP_SERVER_PORT: 8080
      APP_SERVER_READ_HEADER_TIMEOUT: ${APP_SERVER_READ_HEADER_TIMEOUT}
      APP_DB_DSN: ${APP_DB_DSN}
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - pg
    restart: always
    ports:
      - "${APP_SERVER_PORT}:8080"
  pg:
    image: postgres
    env_file:
      - .env
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
      POSTGRES_DB: db
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}" ]
      interval: 5s
      timeout: 10s
      retries: 10

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "19090:9090"


