// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"
	"todolist/internal/storage/ent/task"
	"todolist/internal/storage/schema"

	"github.com/google/uuid"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	taskMixin := schema.Task{}.Mixin()
	taskMixinFields0 := taskMixin[0].Fields()
	_ = taskMixinFields0
	taskFields := schema.Task{}.Fields()
	_ = taskFields
	// taskDescCreateAt is the schema descriptor for create_at field.
	taskDescCreateAt := taskMixinFields0[0].Descriptor()
	// task.DefaultCreateAt holds the default value on creation for the create_at field.
	task.DefaultCreateAt = taskDescCreateAt.Default.(func() time.Time)
	// taskDescUpdateAt is the schema descriptor for update_at field.
	taskDescUpdateAt := taskMixinFields0[1].Descriptor()
	// task.DefaultUpdateAt holds the default value on creation for the update_at field.
	task.DefaultUpdateAt = taskDescUpdateAt.Default.(func() time.Time)
	// task.UpdateDefaultUpdateAt holds the default value on update for the update_at field.
	task.UpdateDefaultUpdateAt = taskDescUpdateAt.UpdateDefault.(func() time.Time)
	// taskDescTitle is the schema descriptor for title field.
	taskDescTitle := taskFields[1].Descriptor()
	// task.TitleValidator is a validator for the "title" field. It is called by the builders before save.
	task.TitleValidator = taskDescTitle.Validators[0].(func(string) error)
	// taskDescCompleted is the schema descriptor for completed field.
	taskDescCompleted := taskFields[3].Descriptor()
	// task.DefaultCompleted holds the default value on creation for the completed field.
	task.DefaultCompleted = taskDescCompleted.Default.(bool)
	// taskDescID is the schema descriptor for id field.
	taskDescID := taskFields[0].Descriptor()
	// task.DefaultID holds the default value on creation for the id field.
	task.DefaultID = taskDescID.Default.(func() uuid.UUID)
}
